/** Read-only inventory of consumer lineup projection paths (Phase 4.6.9.3). */
export const PROJECTION_PATH_INVENTORY = [
  {
    id: 'supabase_event_mapper',
    surface: 'Event repository / API load',
    module: 'data/datasources/supabase/supabase-datasource.mapSupabaseEventRow',
    sourceFields: ['event_lineup_entries', 'event_artists'],
    fallbackOrder: ['structured', 'compatibility', 'empty'],
    usesStructured: true,
    usesPrimaryArtistFallback: false,
    usesTitleInference: false,
    cacheLayer: 'EventRepository memory cache',
  },
  {
    id: 'canonical_event_projection',
    surface: 'Display model / feed / search index input',
    module: 'features/events/formatting/canonical-event-projection',
    sourceFields: ['lineupEntries', 'artists', 'lineup'],
    fallbackOrder: ['structured names', 'compatibility names', 'empty'],
    usesStructured: true,
    usesPrimaryArtistFallback: false,
    usesTitleInference: false,
    cacheLayer: 'EventDisplayModel in feed/detail caches',
  },
  {
    id: 'event_detail_lineup_section',
    surface: 'Event Detail UI',
    module: 'features/event-detail/utils/event-detail-view-model.toLineupSectionViewModel',
    sourceFields: ['lineupEntries', 'knownArtistNames'],
    fallbackOrder: ['structured billing rows', 'knownArtistNames', 'TBA empty'],
    usesStructured: true,
    usesPrimaryArtistFallback: false,
    usesTitleInference: false,
    cacheLayer: 'discovery-event-detail-client',
  },
  {
    id: 'search_index',
    surface: 'Search / discovery text match',
    module: 'features/search/constants.buildEventSearchIndex',
    sourceFields: ['event.artists'],
    fallbackOrder: ['canonical artists from repository load'],
    usesStructured: true,
    usesPrimaryArtistFallback: false,
    usesTitleInference: false,
    cacheLayer: 'EventRepository search index',
  },
  {
    id: 'admin_event_detail',
    surface: 'Admin Event Detail',
    module: 'features/events/services/event-lineup-service',
    sourceFields: ['event_lineup_entries', 'event_artists'],
    fallbackOrder: ['structured admin section', 'flat admin section'],
    usesStructured: true,
    usesPrimaryArtistFallback: false,
    usesTitleInference: false,
    cacheLayer: 'none',
  },
] as const;
