-- Eternal Rave — Sprint 13: production source integration
-- Adds publish_mode, source_roles, country_code, last_error and seeds Bootshaus + Affenkäfig.

alter table public.sources
  add column if not exists country_code text,
  add column if not exists publish_mode text not null default 'manual_review'
    check (publish_mode in ('auto_publish', 'manual_review', 'conditional_review')),
  add column if not exists source_roles text[] not null default '{}',
  add column if not exists last_error text;

create index if not exists sources_publish_mode_idx on public.sources(publish_mode);
create index if not exists sources_source_roles_idx on public.sources using gin(source_roles);

-- Bootshaus Köln — club + venue source, live website fetch
insert into public.sources (
  id,
  slug,
  stable_key,
  display_name,
  name,
  description,
  source_type,
  type,
  base_url,
  source_url,
  website,
  parser_type,
  adapter_key,
  acquisition_strategy,
  polling_interval_minutes,
  priority,
  trust_score,
  requires_authentication,
  enabled,
  active,
  archived,
  review_required,
  publish_mode,
  source_roles,
  source_lifecycle_status,
  connector_type,
  country_code,
  region,
  city,
  language_codes,
  default_timezone,
  source_config,
  metadata,
  notes,
  created_at,
  updated_at
) values (
  'source-bootshaus-koeln',
  'bootshaus-koeln',
  'bootshaus-koeln-website-v1',
  'Bootshaus Köln',
  'Bootshaus Köln',
  'Official public event calendar of Bootshaus Cologne — techno, house and electronic club events.',
  'website',
  'website',
  'https://bootshaus.tv/events/',
  'https://bootshaus.tv/events/',
  'https://bootshaus.tv/events/',
  'html',
  'html',
  'manual',
  360,
  78,
  76,
  false,
  true,
  true,
  false,
  false,
  'auto_publish',
  array['club', 'venue'],
  'active',
  'website',
  'DE',
  'Nordrhein-Westfalen',
  'Köln',
  array['de', 'en'],
  'Europe/Berlin',
  '{
    "reference": { "connectorKey": "club_website" },
    "website": {
      "preferredStrategy": "html_selector",
      "userAgent": "EternalRave-SourceBot/1.0 (+https://eternalrave.app; event-import)",
      "acceptLanguage": "de-DE,de;q=0.9,en;q=0.8",
      "htmlSelector": {
        "baseUrl": "https://bootshaus.tv",
        "eventContainerSelector": ".upcoming-item",
        "titleSelector": ".upcoming-title",
        "dateSelector": ".date-day",
        "monthSelector": ".date-month",
        "timeSelector": ".date-time",
        "venueSelector": ".upcoming-subtitle",
        "imageSelector": "img",
        "imageAttribute": "src",
        "eventUrlSelector": ".upcoming-item",
        "eventUrlAttribute": "href",
        "linkIncludePattern": "^/events/[^/]+$",
        "timezone": "Europe/Berlin",
        "requiredFields": ["title"]
      },
      "limits": {
        "maxEventsPerRun": 50,
        "maxDetailPages": 0,
        "maxPaginationPages": 1,
        "maxPagesPerRun": 1,
        "timeoutMs": 30000
      }
    },
    "regional": { "countryCode": "DE", "languageCode": "de" },
    "publishPolicy": { "mode": "auto_publish", "blockOnDuplicate": true }
  }'::jsonb,
  '{
    "category": "website",
    "connectorKey": "club_website",
    "genreNames": ["Techno", "House", "Electronic"],
    "tags": ["club", "koeln", "techno", "website", "production-source"]
  }'::jsonb,
  'Production source (Sprint 13). Live fetch from bootshaus.tv. Auto-publish enabled.',
  now(),
  now()
)
on conflict (id) do update set
  slug = excluded.slug,
  stable_key = excluded.stable_key,
  display_name = excluded.display_name,
  name = excluded.name,
  description = excluded.description,
  source_type = excluded.source_type,
  type = excluded.type,
  base_url = excluded.base_url,
  source_url = excluded.source_url,
  website = excluded.website,
  parser_type = excluded.parser_type,
  adapter_key = excluded.adapter_key,
  acquisition_strategy = excluded.acquisition_strategy,
  polling_interval_minutes = excluded.polling_interval_minutes,
  priority = excluded.priority,
  trust_score = excluded.trust_score,
  enabled = excluded.enabled,
  active = excluded.active,
  review_required = excluded.review_required,
  publish_mode = excluded.publish_mode,
  source_roles = excluded.source_roles,
  source_lifecycle_status = excluded.source_lifecycle_status,
  connector_type = excluded.connector_type,
  country_code = excluded.country_code,
  region = excluded.region,
  city = excluded.city,
  language_codes = excluded.language_codes,
  default_timezone = excluded.default_timezone,
  source_config = excluded.source_config,
  metadata = excluded.metadata,
  notes = excluded.notes,
  updated_at = now();

-- Affenkäfig — organizer + festival source
-- Domain currently unconfigured; reference HTML stored in source_config until live site is available.
insert into public.sources (
  id,
  slug,
  stable_key,
  display_name,
  name,
  description,
  source_type,
  type,
  base_url,
  source_url,
  website,
  parser_type,
  adapter_key,
  acquisition_strategy,
  polling_interval_minutes,
  priority,
  trust_score,
  requires_authentication,
  enabled,
  active,
  archived,
  review_required,
  publish_mode,
  source_roles,
  source_lifecycle_status,
  connector_type,
  country_code,
  region,
  city,
  language_codes,
  default_timezone,
  source_config,
  metadata,
  notes,
  created_at,
  updated_at
) values (
  'source-affenkaefig',
  'affenkaefig',
  'affenkaefig-website-v1',
  'Affenkäfig',
  'Affenkäfig',
  'Organizer and festival events by Affenkäfig — electronic music in Cologne.',
  'website',
  'website',
  'https://affenkaefig.de/events/',
  'https://affenkaefig.de/events/',
  'https://affenkaefig.de/events/',
  'json-ld',
  'json-ld',
  'manual',
  360,
  72,
  74,
  false,
  true,
  true,
  false,
  false,
  'auto_publish',
  array['organizer', 'festival'],
  'active',
  'website',
  'DE',
  'Nordrhein-Westfalen',
  'Köln',
  array['de'],
  'Europe/Berlin',
  '{
    "reference": {
      "connectorKey": "organizer_website",
      "html": "<!DOCTYPE html><html><head><script type=\\"application/ld+json\\">{\\"@context\\":\\"https://schema.org\\",\\"@graph\\":[{\\"@type\\":\\"Festival\\",\\"name\\":\\"Affenkäfig Open Air 2026\\",\\"startDate\\":\\"2026-08-15T14:00:00+02:00\\",\\"endDate\\":\\"2026-08-16T04:00:00+02:00\\",\\"description\\":\\"Electronic open air festival curated by Affenkäfig.\\",\\"url\\":\\"https://affenkaefig.de/events/open-air-2026\\",\\"organizer\\":{\\"@type\\":\\"Organization\\",\\"name\\":\\"Affenkäfig\\"},\\"location\\":{\\"@type\\":\\"Place\\",\\"name\\":\\"Rheinpark Köln\\",\\"address\\":{\\"addressLocality\\":\\"Köln\\",\\"addressCountry\\":\\"DE\\"}}},{\\"@type\\":\\"MusicEvent\\",\\"name\\":\\"Affenkäfig Warehouse Session\\",\\"startDate\\":\\"2026-09-06T22:00:00+02:00\\",\\"description\\":\\"Warehouse rave series by Affenkäfig.\\",\\"url\\":\\"https://affenkaefig.de/events/warehouse-session\\",\\"organizer\\":{\\"@type\\":\\"Organization\\",\\"name\\":\\"Affenkäfig\\"},\\"location\\":{\\"@type\\":\\"Place\\",\\"name\\":\\"Warehouse Köln\\",\\"address\\":{\\"addressLocality\\":\\"Köln\\",\\"addressCountry\\":\\"DE\\"}}}]}</script></head><body></body></html>"
    },
    "website": {
      "preferredStrategy": "json_ld",
      "userAgent": "EternalRave-SourceBot/1.0 (+https://eternalrave.app; event-import)",
      "acceptLanguage": "de-DE,de;q=0.9,en;q=0.8",
      "limits": {
        "maxEventsPerRun": 50,
        "maxDetailPages": 0,
        "maxPaginationPages": 1,
        "maxPagesPerRun": 1,
        "timeoutMs": 30000
      }
    },
    "regional": { "countryCode": "DE", "languageCode": "de" },
    "publishPolicy": { "mode": "auto_publish", "blockOnDuplicate": true }
  }'::jsonb,
  '{
    "category": "website",
    "connectorKey": "organizer_website",
    "organizerName": "Affenkäfig",
    "genreNames": ["Techno", "House", "Electronic"],
    "tags": ["organizer", "festival", "koeln", "production-source"]
  }'::jsonb,
  'Production source (Sprint 13). Organizer/festival roles. Reference HTML in DB until affenkaefig.de is live.',
  now(),
  now()
)
on conflict (id) do update set
  slug = excluded.slug,
  stable_key = excluded.stable_key,
  display_name = excluded.display_name,
  name = excluded.name,
  description = excluded.description,
  source_type = excluded.source_type,
  type = excluded.type,
  base_url = excluded.base_url,
  source_url = excluded.source_url,
  website = excluded.website,
  parser_type = excluded.parser_type,
  adapter_key = excluded.adapter_key,
  acquisition_strategy = excluded.acquisition_strategy,
  polling_interval_minutes = excluded.polling_interval_minutes,
  priority = excluded.priority,
  trust_score = excluded.trust_score,
  enabled = excluded.enabled,
  active = excluded.active,
  review_required = excluded.review_required,
  publish_mode = excluded.publish_mode,
  source_roles = excluded.source_roles,
  source_lifecycle_status = excluded.source_lifecycle_status,
  connector_type = excluded.connector_type,
  country_code = excluded.country_code,
  region = excluded.region,
  city = excluded.city,
  language_codes = excluded.language_codes,
  default_timezone = excluded.default_timezone,
  source_config = excluded.source_config,
  metadata = excluded.metadata,
  notes = excluded.notes,
  updated_at = now();
