import { writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';

import {
  COLLECTION_SITEMAP_TYPES,
  INDEXABLE_STATIC_ROUTES,
} from '../src/platform/seo/seo-config';

const root = path.resolve(__dirname, '..');
const publicDir = path.join(root, 'public');

function escapeXml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function buildSitemap(baseUrl: string | null, eventIds: string[] = []): string {
  const lastmod = new Date().toISOString().slice(0, 10);
  const urls: Array<{ loc: string; priority: number; changefreq: string }> = [];

  for (const route of INDEXABLE_STATIC_ROUTES) {
    urls.push({
      loc: baseUrl ? `${baseUrl}${route.path}` : route.path,
      priority: route.priority,
      changefreq: route.changefreq,
    });
  }

  for (const type of COLLECTION_SITEMAP_TYPES) {
    urls.push({
      loc: baseUrl ? `${baseUrl}/collection/${type}` : `/collection/${type}`,
      priority: 0.7,
      changefreq: 'daily',
    });
  }

  for (const eventId of eventIds) {
    urls.push({
      loc: baseUrl ? `${baseUrl}/event/${eventId}` : `/event/${eventId}`,
      priority: 0.8,
      changefreq: 'weekly',
    });
  }

  const body = urls
    .map(
      (entry) => `  <url>
    <loc>${escapeXml(entry.loc)}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${entry.changefreq}</changefreq>
    <priority>${entry.priority.toFixed(1)}</priority>
  </url>`,
    )
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`;
}

function buildRobotsTxt(baseUrl: string | null): string {
  const sitemapLine = baseUrl
    ? `Sitemap: ${baseUrl}/sitemap.xml`
    : 'Sitemap: /sitemap.xml';

  return `# Eternal Rave robots.txt — generated by scripts/generate-seo-files.ts
User-agent: *
Allow: /
Disallow: /admin/
Disallow: /admin
Disallow: /_expo/
Disallow: /assets/

${sitemapLine}
`;
}

function main(): void {
  const baseUrl = process.env.EXPO_PUBLIC_WEB_BASE_URL?.replace(/\/$/, '') ?? null;
  const eventIds = process.env.SEO_EVENT_IDS?.split(',').map((id) => id.trim()).filter(Boolean) ?? [];

  mkdirSync(publicDir, { recursive: true });
  writeFileSync(path.join(publicDir, 'sitemap.xml'), buildSitemap(baseUrl, eventIds), 'utf8');
  writeFileSync(path.join(publicDir, 'robots.txt'), buildRobotsTxt(baseUrl), 'utf8');

  console.log('Generated public/robots.txt and public/sitemap.xml');
  if (!baseUrl) {
    console.warn('EXPO_PUBLIC_WEB_BASE_URL not set — sitemap uses relative paths.');
  }
}

main();
