import type { LineupAuditStage } from './lineup-audit-types';

/** Documented runtime pipeline stages for lineup data (read-only audit reference). */
export const LINEUP_PIPELINE_STAGES: LineupAuditStage[] = [
  {
    order: 1,
    name: 'Source configuration',
    module: 'sources table / connector registry',
    inputShape: 'SourceRecord + sourceConfig',
    outputShape: 'connector definition',
    fallbackBehavior: 'default website connector',
    skipConditions: 'inactive source',
    mutationBehavior: 'read_only',
    provenancePreserved: true,
    legacyPath: false,
  },
  {
    order: 6,
    name: 'Connector parser',
    module: 'connectors/website/processor, ticket-platform adapters',
    inputShape: 'raw HTML/JSON',
    outputShape: 'StructuredLineupEntry[] + artistNames[]',
    fallbackBehavior: 'description lineup parser',
    skipConditions: 'detail blocked (ALTCHA)',
    mutationBehavior: 'read_only',
    provenancePreserved: true,
    legacyPath: false,
  },
  {
    order: 7,
    name: 'Normalized candidate',
    module: 'import/normalization/event-normalizer',
    inputShape: 'connector output',
    outputShape: 'NormalizedEventCandidate',
    fallbackBehavior: 'flat artistNames',
    skipConditions: 'validation failure',
    mutationBehavior: 'read_only',
    provenancePreserved: true,
    legacyPath: false,
  },
  {
    order: 8,
    name: 'Import Record persistence',
    module: 'import-repository-impl',
    inputShape: 'ImportRecord',
    outputShape: 'import_records row',
    fallbackBehavior: 'none',
    skipConditions: 'duplicate skip',
    mutationBehavior: 'writes_db',
    provenancePreserved: true,
    legacyPath: false,
  },
  {
    order: 11,
    name: 'Artist candidate validation',
    module: 'events/domain/lineup-artist-quality',
    inputShape: 'string name',
    outputShape: 'accept/reject',
    fallbackBehavior: 'sanitizeLineupArtistNames filter',
    skipConditions: 'billing lines before placeholder check',
    mutationBehavior: 'read_only',
    provenancePreserved: false,
    legacyPath: false,
  },
  {
    order: 12,
    name: 'Artist resolution',
    module: 'import/services/import-title-lineup-resolver',
    inputShape: 'artist name[]',
    outputShape: 'artistIds[]',
    fallbackBehavior: 'create unverified artist',
    skipConditions: 'legacy artifact excluded from exact match',
    mutationBehavior: 'writes_db',
    provenancePreserved: false,
    legacyPath: false,
  },
  {
    order: 13,
    name: 'Structured lineup merge',
    module: 'import/services/import-structured-lineup-from-record',
    inputShape: 'ImportRecord metadata',
    outputShape: 'CanonicalLineupEntry[]',
    fallbackBehavior: 'flyer evidence, description, artistNames lines',
    skipConditions: 'detailBlocked without flyer',
    mutationBehavior: 'read_only',
    provenancePreserved: true,
    legacyPath: false,
  },
  {
    order: 14,
    name: 'Structured persistence',
    module: 'import/services/import-publish-structured-lineup-writer',
    inputShape: 'ResolvedCanonicalLineupEntry[]',
    outputShape: 'event_lineup_entries',
    fallbackBehavior: 'skip when flat+structured unchanged',
    skipConditions: 'needsStructuredLineupReplace false',
    mutationBehavior: 'writes_db',
    provenancePreserved: true,
    legacyPath: false,
  },
  {
    order: 16,
    name: 'Legacy compatibility projection',
    module: 'events/services/event-lineup-service.replaceStructuredLineupFromImport',
    inputShape: 'structured entries',
    outputShape: 'event_artists',
    fallbackBehavior: 'flat import pipeline',
    skipConditions: 'structured repository unavailable',
    mutationBehavior: 'writes_db',
    provenancePreserved: false,
    legacyPath: true,
  },
  {
    order: 17,
    name: 'Event repository projection',
    module: 'data/datasources/supabase/supabase-datasource',
    inputShape: 'event row + lineup joins',
    outputShape: 'Event.lineupEntries + artists',
    fallbackBehavior: 'canonical read: structured → compatibility → empty',
    skipConditions: 'none',
    mutationBehavior: 'read_only',
    provenancePreserved: true,
    legacyPath: false,
  },
  {
    order: 20,
    name: 'Event Detail UI rendering',
    module: 'components/event-detail/LineupSection',
    inputShape: 'LineupSectionViewModel',
    outputShape: 'billingRows or flat artists',
    fallbackBehavior: 'legacy flat artists when no structured entries',
    skipConditions: 'tba empty state',
    mutationBehavior: 'read_only',
    provenancePreserved: false,
    legacyPath: true,
  },
];

export const PARSER_PATH_INVENTORY = [
  {
    id: 'connector_structured',
    module: 'aggregation/connectors/*/processor',
    priority: 1,
    input: 'detail HTML / JSON-LD',
    output: 'lineupEntries metadata',
    createsArtists: false,
    preservesBilling: true,
    canParseDescriptions: false,
    required: true,
  },
  {
    id: 'import_structured_from_record',
    module: 'import/services/import-structured-lineup-from-record',
    priority: 2,
    input: 'ImportRecord',
    output: 'CanonicalLineupEntry[]',
    createsArtists: false,
    preservesBilling: true,
    canParseDescriptions: true,
    required: true,
  },
  {
    id: 'description_lineup_parser',
    module: 'aggregation/domain/lineup-text-parser',
    priority: 3,
    input: 'description text',
    output: 'artist name[]',
    createsArtists: false,
    preservesBilling: 'partial',
    canParseDescriptions: true,
    required: true,
  },
  {
    id: 'title_inference',
    module: 'import/services/import-title-lineup-resolver',
    priority: 99,
    input: 'event title',
    output: 'artistIds (may create)',
    createsArtists: true,
    preservesBilling: false,
    canParseDescriptions: false,
    required: false,
  },
  {
    id: 'flyer_contract',
    module: 'aggregation/connectors/framework/detail-extraction/flyer-lineup-enrichment',
    priority: 4,
    input: 'curated flyer rawText',
    output: 'FlyerLineupCandidate[]',
    createsArtists: false,
    preservesBilling: true,
    canParseDescriptions: false,
    required: false,
  },
  {
    id: 'ops_repair',
    module: 'scripts/operations/_phase469-flyer-reconciliation',
    priority: 0,
    input: 'production DB',
    output: 'mutations',
    createsArtists: true,
    preservesBilling: true,
    canParseDescriptions: false,
    required: false,
    auditOnly: true,
  },
] as const;

export const WRITER_PATH_INVENTORY = [
  {
    id: 'canonical_structured_writer',
    module: 'events/services/canonical-structured-lineup-writer.writeCanonicalStructuredLineup',
    reads: ['ResolvedCanonicalLineupEntry[]', 'existing structured', 'existing flat'],
    writes: ['event_lineup_entries', 'event_lineup_entry_artists', 'event_artists'],
    authoritative: true,
    canDowngrade: false,
    oscillationRisk: 'none',
  },
  {
    id: 'structured_import_candidate',
    module: 'import/services/import-publish-structured-lineup-writer',
    reads: ['ImportRecord', 'existing structured', 'existing flat'],
    writes: [],
    authoritative: false,
    canDowngrade: false,
    oscillationRisk: 'none',
  },
  {
    id: 'title_inference_candidate',
    module: 'import/services/title-inference-candidate',
    reads: ['ImportRecord title'],
    writes: [],
    authoritative: false,
    canDowngrade: false,
    oscillationRisk: 'low',
  },
  {
    id: 'repair_lineup_projection',
    module: 'import/services/import-event-publish-service.repairLineupProjection',
    reads: ['ImportRecord'],
    writes: [],
    authoritative: false,
    canDowngrade: false,
    oscillationRisk: 'none',
  },
  {
    id: 'admin_structured_replace',
    module: 'events/services/event-lineup-service.replaceStructuredLineup',
    reads: ['admin draft entries'],
    writes: [],
    authoritative: false,
    canDowngrade: false,
    oscillationRisk: 'none',
  },
  {
    id: 'sql_backfill',
    module: 'migrations/phase468 structured backfill',
    reads: ['event_artists'],
    writes: ['event_lineup_entries SOLO'],
    authoritative: false,
    canDowngrade: false,
    oscillationRisk: 'low',
    auditOnly: true,
  },
] as const;
