import type { EventCardViewModel, EventListItemViewModel } from '@/components/discovery/view-models';

export const HOME_LOCATION_LABEL = 'Köln, Deutschland';

export const HOME_FILTER_CHIPS = [
  { id: 'all', label: 'Alle', selected: true },
  { id: 'today', label: 'Heute' },
  { id: 'weekend', label: 'Dieses Wochenende' },
  { id: 'techno', label: 'Techno' },
  { id: 'house', label: 'House' },
] as const;

export const featuredIndustrialRebirth: EventCardViewModel = {
  id: 'industrial-rebirth',
  title: 'Industrial Rebirth',
  dateLabel: '14 NOV',
  weekdayLabel: 'FR',
  timeLabel: '23:00',
  venueLabel: 'Gewerbehof',
  cityLabel: 'Köln',
  genreLabels: ['Techno', 'Hard Techno'],
  categoryLabel: 'Techno',
  organizerLabel: 'VOID Events',
  ticketLabel: 'Ab 18,00 €',
  ticketStatus: 'available',
  status: 'upcoming',
  verified: true,
  accessibilityLabel: 'Industrial Rebirth im Gewerbehof Köln',
};

export const nearYouEvents: EventCardViewModel[] = [
  {
    id: 'void-bootshaus',
    title: 'VOID: Techno Saturday',
    dateLabel: '09 NOV',
    weekdayLabel: 'SA',
    timeLabel: '23:00',
    venueLabel: 'Bootshaus',
    cityLabel: 'Köln',
    genreLabels: ['Techno'],
    categoryLabel: 'Techno',
    organizerLabel: 'VOID Events',
    ticketLabel: 'Ab 15,00 €',
    ticketStatus: 'available',
    status: 'upcoming',
    accessibilityLabel: 'VOID Techno Saturday im Bootshaus Köln',
  },
  {
    id: 'odonien-night',
    title: 'Odonien All Night',
    dateLabel: '10 NOV',
    weekdayLabel: 'SO',
    timeLabel: '22:00',
    venueLabel: 'Odonien',
    cityLabel: 'Köln',
    genreLabels: ['Techno', 'Minimal'],
    categoryLabel: 'Minimal',
    ticketLabel: 'Ab 12,00 €',
    ticketStatus: 'limited',
    status: 'upcoming',
    accessibilityLabel: 'Odonien All Night in Köln',
  },
  {
    id: 'gewoelbe-session',
    title: 'Gewölbe Warehouse Session',
    dateLabel: '16 NOV',
    weekdayLabel: 'SA',
    timeLabel: '23:30',
    venueLabel: 'Gewölbe',
    cityLabel: 'Köln',
    genreLabels: ['Industrial'],
    categoryLabel: 'Industrial',
    ticketLabel: 'Ab 14,00 €',
    ticketStatus: 'available',
    status: 'upcoming',
    accessibilityLabel: 'Gewölbe Warehouse Session in Köln',
  },
];

export const tonightListItems: EventListItemViewModel[] = [
  {
    id: 'bootshaus-tonight',
    title: 'Bootshaus: Closing Chapter',
    dateLabel: 'Heute',
    timeLabel: '23:30',
    venueLabel: 'Bootshaus',
    cityLabel: 'Köln',
    genreLabels: ['Techno'],
    status: 'today',
    accessibilityLabel: 'Bootshaus Closing Chapter heute in Köln',
  },
  {
    id: 'berlin-underground',
    title: 'Underground Movement',
    dateLabel: 'Heute',
    timeLabel: '22:00',
    venueLabel: 'Gewerbehof',
    cityLabel: 'Berlin',
    genreLabels: ['Hard Techno'],
    status: 'today',
    accessibilityLabel: 'Underground Movement heute in Berlin',
  },
];

export const weekendEvents: EventCardViewModel[] = [
  {
    id: 'void-berlin',
    title: 'VOID: Berlin Edition',
    dateLabel: '16 NOV',
    weekdayLabel: 'SA',
    timeLabel: '23:00',
    venueLabel: 'Sisyphos',
    cityLabel: 'Berlin',
    genreLabels: ['Techno'],
    categoryLabel: 'Techno',
    organizerLabel: 'VOID Events',
    ticketLabel: 'Ab 20,00 €',
    ticketStatus: 'available',
    status: 'upcoming',
    accessibilityLabel: 'VOID Berlin Edition im Sisyphos',
  },
  {
    id: 'rhein-open-air',
    title: 'Rhein Open Air',
    dateLabel: '17 NOV',
    weekdayLabel: 'SO',
    timeLabel: '14:00',
    venueLabel: 'Rheinpark',
    cityLabel: 'Köln',
    genreLabels: ['Open Air', 'House'],
    categoryLabel: 'Open Air',
    ticketLabel: 'Ab 25,00 €',
    ticketStatus: 'available',
    status: 'upcoming',
    accessibilityLabel: 'Rhein Open Air im Rheinpark Köln',
  },
];
