#!/usr/bin/env bash
# Create app-v2/.env from .env.example using environment variables (never commits secrets).
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
ENV_FILE="${ROOT_DIR}/.env"
EXAMPLE="${ROOT_DIR}/.env.example"

if [[ ! -f "${EXAMPLE}" ]]; then
  echo "Missing ${EXAMPLE}" >&2
  exit 1
fi

: "${EXPO_PUBLIC_SUPABASE_URL:?Set EXPO_PUBLIC_SUPABASE_URL}"
: "${EXPO_PUBLIC_SUPABASE_ANON_KEY:?Set EXPO_PUBLIC_SUPABASE_ANON_KEY}"

cat > "${ENV_FILE}" <<EOF
# Generated by scripts/staging/setup-env.sh — do not commit
EXPO_PUBLIC_GOOGLE_MAPS_API_KEY=${EXPO_PUBLIC_GOOGLE_MAPS_API_KEY:-}

EXPO_PUBLIC_SUPABASE_URL=${EXPO_PUBLIC_SUPABASE_URL}
EXPO_PUBLIC_SUPABASE_ANON_KEY=${EXPO_PUBLIC_SUPABASE_ANON_KEY}

EXPO_PUBLIC_USE_SUPABASE=true
EOF

if [[ -n "${SUPABASE_SERVICE_ROLE_KEY:-}" ]]; then
  cat >> "${ENV_FILE}" <<EOF

# Server-side only — never prefix with EXPO_PUBLIC_
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
EOF
fi

echo "Wrote ${ENV_FILE}"
