export const RAUSGEGANGEN_BASE_URL = 'https://rausgegangen.de';

export const RAUSGEGANGEN_DISCOVERY_USER_AGENT =
  'EternalRave-M9.4A-GermanyDiscovery/1.0 (+research; read-only; no-automation)';

/** Paths that are not city region slugs. */
export const NON_CITY_PATHS = new Set([
  'eventsearch',
  'locations',
  'artists',
  'organizers',
  'blogs',
  'team',
  'jobs',
  'cooperation',
  'login',
  'signup',
  'impressum',
  'datenschutz',
  'agb',
  'about',
  'kontakt',
  'presse',
  'werben',
  'tickets',
  'en',
  'de',
  'api',
  'static',
  'events',
  'organizations',
  'pages',
  'articles',
  'topics',
  'sitemap.xml',
]);

/** Major German metros prioritized for stratified Germany-wide qualification. */
export const PRIORITY_GERMAN_CITY_SLUGS = [
  'cologne',
  'berlin',
  'hamburg',
  'muenchen',
  'frankfurt',
  'stuttgart',
  'leipzig',
  'dortmund',
  'essen',
  'duesseldorf',
  'bonn',
  'bremen',
  'hannover',
  'nuernberg',
  'dresden',
  'karlsruhe',
  'mannheim',
  'aachen',
  'bochum',
  'muenster',
  'wiesbaden',
  'mainz',
  'kiel',
  'freiburg',
  'rostock',
  'potsdam',
  'magdeburg',
  'erfurt',
  'saarbruecken',
  'kassel',
  'heidelberg',
  'augsburg',
  'wuppertal',
  'bielefeld',
  'chemnitz',
  'moenchengladbach',
  'krefeld',
  'luebeck',
  'oberhausen',
  'oldenburg',
  'osnabrueck',
  'paderborn',
  'trier',
  'siegen',
  'jena',
  'kaiserslautern',
  'regensburg',
  'ulm',
  'ingolstadt',
  'heilbronn',
];

export const SLUG_TO_DISPLAY_NAME: Record<string, string> = {
  cologne: 'Köln',
  muenchen: 'München',
  duesseldorf: 'Düsseldorf',
  muenster: 'Münster',
  nuernberg: 'Nürnberg',
  saarbruecken: 'Saarbrücken',
  luebeck: 'Lübeck',
  moenchengladbach: 'Mönchengladbach',
  koeln: 'Köln',
};

export const DEFAULT_DISCOVERY_BOUNDS = {
  maxRegions: 45,
  maxListingPagesPerRegion: 1,
  maxDetailCandidates: 2500,
  listingConcurrency: 2,
  detailConcurrency: 3,
  requestDelayMs: 250,
  fetchTimeoutMs: 25000,
  maxRetries: 2,
};
